from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd, cwd + "/include"]

# HTTP 服务器源文件
src = Glob("http_service.c")
src += Glob("src/*.c")
src += Glob("src/*.cpp")

group = DefineGroup("app_http_server", src, depend = [""], CPPPATH = CPPPATH)

objs = [group]

# 递归处理子目录（如果有）
list = os.listdir(cwd)
for item in list:
    if os.path.isdir(os.path.join(cwd, item)) and os.path.isfile(os.path.join(cwd, item, "SConscript")):
        objs = objs + SConscript(os.path.join(item, "SConscript"))

Return("objs")


